- name: vm
  hosts: all
  become: yes
  vars:
    vmpkg:
    - virt-manager
    - qemu-system
    - libvirt-daemon-system
    - qemu-utils
    - virtualbox
    - gnome-boxes

  tasks:
  - name: Install vm soft
    package:
      pkg: "{{vmpkg}}"
      state: present

  - name: Add user to vm groups
    ansible.builtin.shell:
      cmd: "usermod -aG libvirt,kvm,vboxusers {{ansible_user}}"

  - name: reboot
    ansible.builtin.reboot:
      